---
title: "Gene Combined pvalues"
author: "Noor Pratap Singh"
date: "10/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```


```{r}
suppressPackageStartupMessages(source("tree_helper_function.R"))
# load("environment/brain_sim/final1_NA/tAfterNoStop.RData")
# load("environment/brain_sim/final1_NA/tAfter.RData")
# load("environment/brain_sim/tree.RData")
# load("environment/brain_sim/mapDf.RData")
# load("environment/brain_sim/yAll.RData")
# load("environment/brain_sim/y.RData")
load("environment/brain_sim/simulate.rda")
load("environment/brain_sim/final1_NA/gene_group/combPvalsqvalNoStop.Rdata")
load("environment/brain_sim/final1_NA/gene_group/combPvalsqval.Rdata")
load("environment/brain_sim/final1_NA/gene_group/combPvalstxp.Rdata")
```

### Computing gene groups
```{r}
# qvalNodes <- lapply(tAfter, function(ta) c(ta[["negNodeO"]],ta[["candNodeO"]]))
# qvalNodesNoStop <- lapply(tAfterNoStop, function(ta) c(ta[["negNodeO"]],ta[["candNodeO"]]))
# load("environment/brain_sim/gene_group/txpGeneGroup.Rdata")
# 
# qvalGeneGroup <- mclapply(qvalNodes, function(nodes) getGeneGroup(tree, nodes, mapDf), mc.cores = 3)
# save(qvalGeneGroup, file = "environment/brain_sim/final1_NA/gene_group/qvalGeneGroup.Rdata")
# qvalNoStopGeneGroup <- mclapply(qvalNodesNoStop, function(nodes) getGeneGroup(tree, nodes, mapDf), mc.cores = 3)
# save(qvalNoStopGeneGroup, file = "environment/brain_sim/final1_NA/gene_group/qvalNoStopGeneGroup.Rdata")
```

### Computing pvalues
```{r}
# yAll <- labelKeep(yAll)
# set.seed(100)
# yAll <- swish(yAll, x="condition")
# load("environment/brain_sim/final1_NA/gene_group/qvalGeneGroup.Rdata")
# combPvalsqval <- list()
# combPvalsqval[["harmonic_BH"]] <- mclapply(qvalGeneGroup, function(gG) getGeneCombPvalue(gG, yAll, "harmonic", "BH"), mc.cores = 3)
# save(combPvalsqval, file="environment/brain_sim/final1_NA/gene_group/combPvalsqval.Rdata")
# for(i in seq_along(combPvalsqval[["harmonic_BH"]]))
#     hist(combPvalsqval[["harmonic_BH"]][[i]])
# 
# combPvalsqval[["fisher_BH"]] <- mclapply(qvalGeneGroup, function(gG) getGeneCombPvalue(gG, yAll, "fisher", "BH"), mc.cores = 3)
# for(i in seq_along(combPvalsqval[["fisher_BH"]]))
#     hist(combPvalsqval[["fisher_BH"]][[i]])
# save(combPvalsqval, file="environment/brain_sim/final1_NA/gene_group/combPvalsqval.Rdata")
```

### Computing pvalues
```{r}
# load("environment/brain_sim/final1_NA/gene_group/qvalNoStopGeneGroup.Rdata")
# combPvalsqvalNoStop <- list()
# combPvalsqvalNoStop[["harmonic_BH"]] <- mclapply(qvalNoStopGeneGroup, function(gG) getGeneCombPvalue(gG, yAll, "harmonic", "BH"), mc.cores = 3)
# save(combPvalsqvalNoStop, file="environment/brain_sim/final1_NA/gene_group/combPvalsqvalNoStop.Rdata")
# for(i in seq_along(combPvalsqvalNoStop[["harmonic_BH"]]))
#     hist(combPvalsqvalNoStop[["harmonic_BH"]][[i]])
# 
# combPvalsqvalNoStop[["fisher_BH"]] <- mclapply(qvalNoStopGeneGroup, function(gG) getGeneCombPvalue(gG, yAll, "fisher", "BH"), mc.cores = 3)
# for(i in seq_along(combPvalsqvalNoStop[["fisher_BH"]]))
#     hist(combPvalsqvalNoStop[["fisher_BH"]][[i]])
# save(combPvalsqvalNoStop, file="environment/brain_sim/final1_NA/gene_group/combPvalsqvalNoStop.Rdata")
```

### Computing pvalues
```{r}
# y <- labelKeep(y)
# set.seed(100)
# y <- swish(y, x="condition")
# 
# load("environment/brain_sim/gene_group/txpGeneGroup.Rdata")
# combPvalstxp <- list()
# combPvalstxp[["harmonic_BH"]] <-  getGeneCombPvalue(txpGeneGroup, y, "harmonic", "BH")
# hist(combPvalstxp[["harmonic_BH"]])
# save(combPvalstxp, file="environment/brain_sim/final1_NA/gene_group/combPvalstxp.Rdata")
# 
# combPvalstxp[["fisher_BH"]] <- getGeneCombPvalue(txpGeneGroup, y, "fisher", "BH")
# hist(combPvalstxp[["fisher_BH"]])
# save(combPvalstxp, file="environment/brain_sim/final1_NA/gene_group/combPvalstxp.Rdata")
```

```{r}
alphas <- c(0.01, 0.05, 0.1)
dfGeneMet <- data.frame(Method=character(), Metric=character(), FDR_0.01 = numeric(), FDR_0.05 = numeric(), FDR_0.10 = numeric())

for(i in seq_along(combPvalstxp)[c(1,2)])
{
    genes <- names(combPvalstxp[[i]])
    if(i==1)
        genes <- unlist(strsplit(genes,"*.p.hmp"))
    trueDTU <- intersect(dtu.genes, genes)
    pval <- combPvalstxp[[i]]
    stats <-  sapply(alphas, function(alpha) computeTPFP(match(trueDTU, genes), which(pval <= alpha), logFC=pval, "all"))
    colnames(stats) <- colnames(dfGeneMet)[c(3:5)]
    n <- paste("txp",names(combPvalstxp)[i],sep = "_")
    stats <- cbind(Method=rep(n,2), Metric = c("FDR", "TPR"), stats)
    dfGeneMet <- rbind(dfGeneMet, stats)
}

```

```{r}
for(i in seq_along(combPvalsqval))
{
    stats <- sapply(seq_along(combPvalsqval[[i]]), function(j) {
        genes <- names(combPvalsqval[[i]][[j]])
        if(i==1)
            genes <- unlist(strsplit(genes,"*.p.hmp"))
        trueDTU <- intersect(dtu.genes, genes)
        pval <- combPvalsqval[[i]][[j]]
        print(length(pval))
        print(length(trueDTU))
        print(j)
        computeTPFP(match(trueDTU, genes), which(pval <= alphas[j]), logFC=pval, "all")
    })

    colnames(stats) <- colnames(dfGeneMet)[c(3:5)]
    n <- paste("qval",names(combPvalsqval)[i],sep = "_")
    stats <- cbind(Method=rep(n,2), Metric = c("FDR", "TPR"), stats)
    dfGeneMet <- rbind(dfGeneMet, stats)
}
```

```{r}
for(i in seq_along(combPvalsqvalNoStop)[c(1,2)])
{
    stats <- sapply(seq_along(combPvalsqvalNoStop[[i]]), function(j) {
        genes <- names(combPvalsqvalNoStop[[i]][[j]])
        if(i==1)
            genes <- unlist(strsplit(genes,"*.p.hmp"))
        trueDTU <- intersect(dtu.genes, genes)
        pval <- combPvalsqvalNoStop[[i]][[j]]
        print(length(pval))
        print(length(trueDTU))
        print(j)

        computeTPFP(match(trueDTU, genes), which(pval <= alphas[j]), logFC=pval, "all")
    })

    colnames(stats) <- colnames(dfGeneMet)[c(3:5)]
    n <- paste("qvalNoStop",names(combPvalsqvalNoStop)[i],sep = "_")
    stats <- cbind(Method=rep(n,2), Metric = c("FDR", "TPR"), stats)
    dfGeneMet <- rbind(dfGeneMet, stats)
}
print(dfGeneMet)
save(dfGeneMet, file = "environment/brain_sim/final1_NA/gene_group/dfGeneMet.Rdata")

df_fix <- fixDf(dfGeneMet)
ggplot(df_fix, aes(FDR, TPR, color=Method)) + geom_point() + geom_line()
```


```{r}
trueDTUTxp <- intersect(dtu.genes, names(combPvalstxp[[2]]))
trueDTUNS <- intersect(dtu.genes, names(combPvalsqvalNoStop[[2]][[3]]))
commDTUs <- intersect(trueDTUNS, trueDTUTxp) ###True DTUs

genesOnlyTxp <- intersect(commDTUs,names(combPvalstxp[[2]])[which(combPvalstxp[[2]] <= 0.1)])
genesOnlyNoStop <- intersect(commDTUs,names(combPvalsqvalNoStop[[2]][[3]])[which(combPvalsqvalNoStop[[2]][[3]] <= 0.1)])

qvalMissing <- setdiff(genesOnlyTxp, genesOnlyNoStop)
nostopMissing <- setdiff(genesOnlyNoStop, genesOnlyTxp)
#
print(sum(setdiff(txpMissing, qvalMissing) %in% genes[which(combPvalsqvalNoStop[[3]][[3]] <= 0.1)]))
combPvalsqvalNoStop[[2]][[3]][qvalMissing]

df <- data.frame(txp=rep(1,length(qvalMissing)), qval=rep(1,length(qvalMissing)))
rownames(df) <- qvalMissing
df[qvalMissing,1] <- combPvalstxp[[2]][qvalMissing]
df[qvalMissing,2] <- combPvalsqvalNoStop[[2]][[3]][qvalMissing]

i=3
sapply(qvalMissing, function(q) mcols(y)[txpGeneGroup[[q]],"pvalue"])
sapply(qvalMissing[i], function(q) mcols(yAll)[qvalNoStopGeneGroup[[3]][[q]],"pvalue"])
sapply(qvalMissing, function(q) mcols(yAll)[Descendants(tree,qvalNoStopGeneGroup[[3]][[q]])[[1]],"pvalue"])

mcols(y)[txpGeneGroup[[qvalMissing[i]]],"pvalue"]
mcols(yAll)[qvalNoStopGeneGroup[[3]][[qvalMissing[i]]],"pvalue"]
mcols(yAll)[Descendants(tree,qvalNoStopGeneGroup[[3]][[qvalMissing[i]]])[[1]],"pvalue"]

inds <- which(df[,2] > 0.2)
i=inds[4]
mcols(y)[txpGeneGroup[[qvalMissing[i]]],"pvalue"]
mcols(yAll)[qvalNoStopGeneGroup[[3]][[qvalMissing[i]]],"pvalue"]
mcols(yAll)[Descendants(tree,qvalNoStopGeneGroup[[3]][[qvalMissing[i]]])[[1]],"pvalue"]

i=inds[5]
mcols(y)[txpGeneGroup[[qvalMissing[i]]],"pvalue"]
mcols(yAll)[qvalNoStopGeneGroup[[3]][[qvalMissing[i]]],"pvalue"]
mcols(yAll)[Descendants(tree,qvalNoStopGeneGroup[[3]][[qvalMissing[i]]])[[1]],"pvalue"]

i=inds[6]
mcols(y)[txpGeneGroup[[qvalMissing[i]]],"pvalue"]
mcols(yAll)[qvalNoStopGeneGroup[[3]][[qvalMissing[i]]],"pvalue"]
mcols(yAll)[Descendants(tree,qvalNoStopGeneGroup[[3]][[qvalMissing[i]]])[[1]],"pvalue"]

sapply(inds, function(i) {
    txps <- txpGeneGroup[[qvalMissing[i]]]
    pvals <- mcols(y)[txps, "pvalue"]
    pInds <- which(!is.na(pvals))
    logFC <- mcols(y)[txps, "log2FC"]
    pos <- sum(logFC[pInds] > 0)
    neg <- sum(logFC[pInds] < 0)

    if(pos > 0 & neg > 0)
        return(T)
    return(F)
})
#
# fpsQ <- setdiff(genes[which(combPvalsqvalNoStop[[1]][[3]] <= 0.1)],trueDTU)
```
Around genes with dtu identified by the method though

```{r}
posNodes <- which(abs(logFCNodes) > rootFC-0.001)
cAf <- intersect(tAfter[[3]][["candNodeO"]], posNodes)
cAfNoStop <- intersect(tAfterNoStop[[3]][["candNodeO"]], posNodes)
length(intersect(cAf, cAfNoStop))
```