---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```


#### Loading Packages
```{r}
suppressPackageStartupMessages(source("tree_helper_function.R"))
suppressPackageStartupMessages(source("tree_term_climb.R"))
load("environment/brain_sim/yAll.RData")
load("environment/brain_sim/y.RData")
load("environment/brain_sim/tree.RData")
```

#### Distribution of signs and levels
```{r}
minInfRV <- 3
nLeaf <- length(tree$tip)
#mIRV_cut <- cut(mIRVDiff[nLeaf+1:tree$Nnode], breaks = quantile(mIRVDiff[nLeaf+1:tree$Nnode], 0:4/4), include.lowest = T)
#print(table(mIRV_cut))

#termThresh <- quantile(mIRVDiff[nLeaf+1:tree$Nnode], 0.75)
signs <- computeSign(yAll, "condition")
print(table(signs))
levels <- node.depth(tree, 2)
levels <- ifelse(levels > 4, 5, levels)
print(table(levels))
print(table(signs, levels))
```

<!-- #### Running IHW -->
<!-- ```{r} -->
<!-- df <- data.frame(IRVCut = cut(mcols(yAll)[["meanInfRV"]], breaks = quantile(mcols(yAll)[["meanInfRV"]], 0:4/4), include.lowest = T), -->
<!--                  levels, pvalue = mcols(yAll)[["pvalue"]], infRVs = mcols(yAll)[["meanInfRV"]]) -->
<!-- table(df[["IRVCut"]]) -->
<!-- res <- ihw(pvalue ~ IRVCut,  data = df, -->
<!--            alpha = 0.1, -->
<!--            covariate_type = "ordinal") -->
<!-- print(sum(mcols(yAll)[["qvalue"]] < 0.1)) -->
<!-- print(rejections(res)) -->
<!-- plot(res) -->
<!-- ``` -->

#### Running tree Terminus Climber  
```{r}
# print("tbeforeIHW")
# print(system.time(tbeforeIHW <- runTreeTermAlphas(tree, yAll, "condition", minInfRV, pCutOff = 0.05, pChild = 0.05, runType = c("b"), corr = c("IHW"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T)))
# save(tbeforeIHW, file = "environment/brain_sim/tbeforeIHW.RData")
# 
# print("tbeforeIHWNoStop")
# print(system.time(tbeforeIHWNoStop <- runTreeTermAlphas(tree, yAll, "condition", -100000, pCutOff = 0.05, pChild = 0.05, runType = c("b"), corr = c("IHW"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T, cSign = F)))
# save(tbeforeIHWNoStop, file = "environment/brain_sim/tbeforeIHWNoStop.RData")
# 
# print("tbeforeIHWNoThresh")
# print(system.time(tbeforeIHWNoSign <- runTreeTermAlphas(tree, yAll, "condition", 0.20, pCutOff = 0.05, pChild = 0.05, runType = c("b"), corr = c("IHW"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T, cSign = F)))
# save(tbeforeIHWNoSign, file = "environment/brain_sim/tbeforeIHWNoSign.RData")
```


<!-- ### Qvalue -->
<!-- ```{r} -->
<!-- print("tbeforeqval") -->
<!-- print(system.time(tbeforeqval <- runTreeTermAlphas(tree, yAll, "condition", minInfRV, pCutOff = 0.05, pChild = 0.05, runType = c("b"), corr = c("qvalue"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T))) -->
<!-- save(tbeforeqval, file = "environment/brain_sim/tbeforeqval.RData") -->

<!-- print("tbeforeqvalNoStop") -->
<!-- print(system.time(tbeforeqvalNoStop <- runTreeTermAlphas(tree, yAll, "condition", -100000, pCutOff = 0.05, pChild = 0.05, runType = c("b"), corr = c("qvalue"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T, cSign = F))) -->
<!-- save(tbeforeqvalNoStop, file = "environment/brain_sim/tbeforeqvalNoStop.RData") -->

<!-- print("tbeforeqvalNoThresh") -->
<!-- print(system.time(tbeforeqvalNoSign <- runTreeTermAlphas(tree, yAll, "condition", 0.20, pCutOff = 0.05, pChild = 0.05, runType = c("b"), corr = c("qvalue"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T, cSign = F))) -->
<!-- save(tbeforeqvalNoSign, file = "environment/brain_sim/tbeforeqvalNoSign.RData") -->
<!-- ``` -->

#### BH
```{r}
print("tbeforeBH")
print(system.time(tbeforeBH <- runTreeTermAlphas(tree, yAll, "condition", minInfRV, pCutOff = 0.05, pChild = 0.05, runType = c("b"), corr = c("BH"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T)))
save(tbeforeBH, file = "environment/brain_sim/tbeforeBH.RData")

print("tbeforeBHNoStop")
print(system.time(tbeforeBHNoStop <- runTreeTermAlphas(tree, yAll, "condition", -100000, pCutOff = 0.05, pChild = 0.05, runType = c("b"), corr = c("BH"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T, cSign = F)))
save(tbeforeBHNoStop, file = "environment/brain_sim/tbeforeBHNoStop.RData")

print("tbeforeBHNoThresh")
print(system.time(tbeforeBHNoSign <- runTreeTermAlphas(tree, yAll, "condition", 0.20, pCutOff = 0.05, pChild = 0.05, runType = c("b"), corr = c("BH"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T, cSign = F)))
save(tbeforeBHNoSign, file = "environment/brain_sim/tbeforeBHNoSign.RData")
```

#### Distribution of nodes
```{r}
# print(sapply(c(0.01, 0.05, 0.1), function(x) sum(mcols(y)[["qvalue"]] < x)))
# 
# print(sapply(tBefore, function(node) table(levels[node[["candNodeO"]]])))
# print(sapply(tAfter, function(node) table(levels[node[["candNodeO"]]])))
# 
# print(sapply(tBeforeNoStop, function(node) table(levels[node[["candNodeO"]]])))
# print(sapply(tAfterNoStop, function(node) table(levels[node[["candNodeO"]]])))
```
