```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

```{r}
setwd('/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
load("environment/brain_sim_nodtu/mode=gc_bias/mapDf.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/treeCons.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/treeCons0.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/treeMC0.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/treeMC.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/treeCor.RData")
suppressPackageStartupMessages(source("tree_helper_function.R"))
suppressPackageStartupMessages(source("brain_simulation_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/tree_analysis/tree_filter.R"))
```

```{r}
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/yAggMeanInfNS0.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/yAggConsNS0.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/yAggMeanInfNS.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/yAggConsNS.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/yAggCorNS.RData")
```

<!-- #### Gamma 0.1 -->
<!-- ```{r} -->
<!-- gamma <- 0.1 -->
<!-- dfDepth <- data.frame(matrix(nrow=0, ncol=4)) -->
<!-- dCutsD <- list() -->
<!-- dCutsD[["gamma=0.1"]] <- list() -->
<!-- colnames(dfDepth) <- c("Type", "Value", "nCuts", "gamma") -->
<!-- l <- length(treeCons0$tip) -->

<!-- globArr <- rep(-100, l+treeCons0$Nnode) -->
<!-- descL <- sapply(Descendants(treeCons0, seq(l+treeCons0$Nnode)), length) -->
<!-- obj <- mcols(yAggConsNS0)[["meanInfRV"]] + gamma*node.depth(treeCons0,2) -->
<!-- val <- findOptSum(treeCons0, obj, l+1, descL) -->
<!-- dCutsD[["gamma=0.1"]][["Cons0"]] <- findCuts(treeCons0, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=0.1"]][["Cons0"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "Cons0", Value = val,  -->
<!--        nCuts = length(dCutsD[["gamma=0.1"]][["Cons0"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeCons$Nnode) -->
<!-- descL <- sapply(Descendants(treeCons, seq(l+treeCons$Nnode)), length) -->
<!-- obj <- mcols(yAggConsNS)[["meanInfRV"]] + gamma*node.depth(treeCons,2) -->
<!-- val <- findOptSum(treeCons, obj, l+1, descL) -->
<!-- dCutsD[["gamma=0.1"]][["Cons"]] <- findCuts(treeCons, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=0.1"]][["Cons"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "Cons", Value = val,  -->
<!--                   nCuts = length(dCutsD[["gamma=0.1"]][["Cons"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeMeanInf0$Nnode) -->
<!-- descL <- sapply(Descendants(treeMeanInf0, seq(l+treeMeanInf0$Nnode)), length) -->
<!-- obj <- mcols(yAggMeanInfNS0)[["meanInfRV"]] + gamma*node.depth(treeMeanInf0,2) -->
<!-- val <- findOptSum(treeMeanInf0, obj, l+1, descL) -->
<!-- dCutsD[["gamma=0.1"]][["MeanInf0"]] <- findCuts(treeMeanInf0, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=0.1"]][["MeanInf0"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf0", Value = val,  -->
<!--                  nCuts = length(dCutsD[["gamma=0.1"]][["MeanInf0"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeMeanInf$Nnode) -->
<!-- descL <- sapply(Descendants(treeMeanInf, seq(l+treeMeanInf$Nnode)), length) -->
<!-- obj <- mcols(yAggMeanInfNS)[["meanInfRV"]]  + gamma*node.depth(treeMeanInf0,2) -->
<!-- val <- findOptSum(treeMeanInf, obj, l+1, descL) -->
<!-- dCutsD[["gamma=0.1"]][["MeanInf"]] <- findCuts(treeMeanInf, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=0.1"]][["MeanInf"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf", Value = val,  -->
<!--            nCuts = length(dCutsD[["gamma=0.1"]][["MeanInf"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeCor$Nnode) -->
<!-- descL <- sapply(Descendants(treeCor, seq(l+treeCor$Nnode)), length) -->
<!-- obj <- mcols(yAggCorNS)[["meanInfRV"]]  + gamma*node.depth(treeCor,2) -->
<!-- val <- findOptSum(treeCor, obj, l+1, descL) -->
<!-- dCutsD[["gamma=0.1"]][["Cor"]] <- findCuts(treeCor, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=0.1"]][["Cor"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "Cor", Value = val,  -->
<!--                  nCuts = length(dCutsD[["gamma=0.1"]][["Cor"]]), gamma=gamma)) -->
<!-- gc() -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- print(dfDepth) -->
<!-- ``` -->
<!-- #### Gamma 0.5 -->
<!-- ```{r} -->
<!-- #load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- #dfDepth <- data.frame(matrix(nrow=0, ncol=4)) -->
<!-- #colnames(dfDepth) <- c("Type", "Value", "nCuts", "gamma") -->
<!-- gamma <- 0.5 -->
<!-- dCutsD[["gamma=0.5"]] <- list() -->

<!-- globArr <- rep(-100, l+treeCons0$Nnode) -->
<!-- descL <- sapply(Descendants(treeCons0, seq(l+treeCons0$Nnode)), length) -->
<!-- obj <- mcols(yAggConsNS0)[["meanInfRV"]] + gamma*node.depth(treeCons0,2) -->
<!-- val <- findOptSum(treeCons0, obj, l+1, descL) -->
<!-- dCutsD[["gamma=0.5"]][["Cons0"]] <- findCuts(treeCons0, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=0.5"]][["Cons0"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "Cons0", Value = val,  -->
<!--        nCuts = length(dCutsD[["gamma=0.5"]][["Cons0"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeCons$Nnode) -->
<!-- descL <- sapply(Descendants(treeCons, seq(l+treeCons$Nnode)), length) -->
<!-- obj <- mcols(yAggConsNS)[["meanInfRV"]] + gamma*node.depth(treeCons,2) -->
<!-- val <- findOptSum(treeCons, obj, l+1, descL) -->
<!-- dCutsD[["gamma=0.5"]][["Cons"]] <- findCuts(treeCons, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=0.5"]][["Cons"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "Cons", Value = val,  -->
<!--                   nCuts = length(dCutsD[["gamma=0.5"]][["Cons"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeMeanInf0$Nnode) -->
<!-- descL <- sapply(Descendants(treeMeanInf0, seq(l+treeMeanInf0$Nnode)), length) -->
<!-- obj <- mcols(yAggMeanInfNS0)[["meanInfRV"]] + gamma*node.depth(treeMeanInf0,2) -->
<!-- val <- findOptSum(treeMeanInf0, obj, l+1, descL) -->
<!-- dCutsD[["gamma=0.5"]][["MeanInf0"]] <- findCuts(treeMeanInf0, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=0.5"]][["MeanInf0"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf0", Value = val,  -->
<!--                  nCuts = length(dCutsD[["gamma=0.5"]][["MeanInf0"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeMeanInf$Nnode) -->
<!-- descL <- sapply(Descendants(treeMeanInf, seq(l+treeMeanInf$Nnode)), length) -->
<!-- obj <- mcols(yAggMeanInfNS)[["meanInfRV"]]  + gamma*node.depth(treeMeanInf,2) -->
<!-- val <- findOptSum(treeMeanInf, obj, l+1, descL) -->
<!-- dCutsD[["gamma=0.5"]][["MeanInf"]] <- findCuts(treeMeanInf, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=0.5"]][["MeanInf"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf", Value = val,  -->
<!--            nCuts = length(dCutsD[["gamma=0.5"]][["MeanInf"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeCor$Nnode) -->
<!-- descL <- sapply(Descendants(treeCor, seq(l+treeCor$Nnode)), length) -->
<!-- obj <- mcols(yAggCorNS)[["meanInfRV"]]  + gamma*node.depth(treeCor,2) -->
<!-- val <- findOptSum(treeCor, obj, l+1, descL) -->
<!-- dCutsD[["gamma=0.5"]][["Cor"]] <- findCuts(treeCor, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=0.5"]][["Cor"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "Cor", Value = val,  -->
<!--                  nCuts = length(dCutsD[["gamma=0.5"]][["Cor"]]), gamma=gamma)) -->
<!-- gc() -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- print(dfDepth) -->
<!-- ``` -->

<!-- #### Gamma 1 -->
<!-- ```{r} -->
<!-- gamma <- 1 -->
<!-- dCutsD[["gamma=1"]] <- list() -->

<!-- globArr <- rep(-100, l+treeCons0$Nnode) -->
<!-- descL <- sapply(Descendants(treeCons0, seq(l+treeCons0$Nnode)), length) -->
<!-- obj <- mcols(yAggConsNS0)[["meanInfRV"]] + gamma*node.depth(treeCons0,2) -->
<!-- val <- findOptSum(treeCons0, obj, l+1, descL) -->
<!-- dCutsD[["gamma=1"]][["Cons0"]] <- findCuts(treeCons0, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma"]][["Cons0"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "Cons0", Value = val,  -->
<!--        nCuts = length(dCutsD[["gamma=1"]][["Cons0"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeCons$Nnode) -->
<!-- descL <- sapply(Descendants(treeCons, seq(l+treeCons$Nnode)), length) -->
<!-- obj <- mcols(yAggConsNS)[["meanInfRV"]] + gamma*node.depth(treeCons,2) -->
<!-- val <- findOptSum(treeCons, obj, l+1, descL) -->
<!-- dCutsD[["gamma=1"]][["Cons"]] <- findCuts(treeCons, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=1"]][["Cons"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "Cons", Value = val,  -->
<!--                   nCuts = length(dCutsD[["gamma=1"]][["Cons"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeMeanInf0$Nnode) -->
<!-- descL <- sapply(Descendants(treeMeanInf0, seq(l+treeMeanInf0$Nnode)), length) -->
<!-- obj <- mcols(yAggMeanInfNS0)[["meanInfRV"]] + gamma*node.depth(treeMeanInf0,2) -->
<!-- val <- findOptSum(treeMeanInf0, obj, l+1, descL) -->
<!-- dCutsD[["gamma=1"]][["MeanInf0"]] <- findCuts(treeMeanInf0, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=1"]][["MeanInf0"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf0", Value = val,  -->
<!--                  nCuts = length(dCutsD[["gamma=1"]][["MeanInf0"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeMeanInf$Nnode) -->
<!-- descL <- sapply(Descendants(treeMeanInf, seq(l+treeMeanInf$Nnode)), length) -->
<!-- obj <- mcols(yAggMeanInfNS)[["meanInfRV"]]  + gamma*node.depth(treeMeanInf,2) -->
<!-- val <- findOptSum(treeMeanInf, obj, l+1, descL) -->
<!-- dCutsD[["gamma=1"]][["MeanInf"]] <- findCuts(treeMeanInf, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=1"]][["MeanInf"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf", Value = val,  -->
<!--            nCuts = length(dCutsD[["gamma=1"]][["MeanInf"]]), gamma=gamma)) -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- gc() -->

<!-- globArr <- rep(-100, l+treeCor$Nnode) -->
<!-- descL <- sapply(Descendants(treeCor, seq(l+treeCor$Nnode)), length) -->
<!-- obj <- mcols(yAggCorNS)[["meanInfRV"]]  + gamma*node.depth(treeCor,2) -->
<!-- val <- findOptSum(treeCor, obj, l+1, descL) -->
<!-- dCutsD[["gamma=1"]][["Cor"]] <- findCuts(treeCor, globArr, obj, l+1, descL) -->
<!-- length(dCutsD[["gamma=1"]][["Cor"]]) -->
<!-- dfDepth <- rbind(dfDepth, data.frame(Type = "Cor", Value = val,  -->
<!--                  nCuts = length(dCutsD[["gamma=1"]][["Cor"]]), gamma=gamma)) -->
<!-- gc() -->
<!-- save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData") -->
<!-- print(dfDepth) -->
<!-- ``` -->

#### Gamma 5
```{r}
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData")
gamma <- 5
dCutsD[["gamma=5"]] <- list()
l <- length(treeCons0$tip)
globArr <- rep(-100, l+treeCons0$Nnode)
descL <- sapply(Descendants(treeCons0, seq(l+treeCons0$Nnode)), length)
obj <- mcols(yAggConsNS0)[["meanInfRV"]] + gamma*node.depth(treeCons0,2)
val <- findOptSum(treeCons0, obj, l+1, descL)
dCutsD[["gamma=5"]][["Cons0"]] <- findCuts(treeCons0, globArr, obj, l+1, descL)
length(dCutsD[["gamma=5"]][["Cons0"]])
# dfDepth <- rbind(dfDepth, data.frame(Type = "Cons0", Value = val,
#        nCuts = length(dCutsD[["gamma=5"]][["Cons0"]]), gamma=gamma))
dfDepth <- data.frame(Type = "Cons0", Value = val, 
                      nCuts = length(dCutsD[["gamma=5"]][["Cons0"]]), gamma = gamma)

save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData")
gc()

globArr <- rep(-100, l+treeCons$Nnode)
descL <- sapply(Descendants(treeCons, seq(l+treeCons$Nnode)), length)
obj <- mcols(yAggConsNS)[["meanInfRV"]] + gamma*node.depth(treeCons,2)
val <- findOptSum(treeCons, obj, l+1, descL)
dCutsD[["gamma=5"]][["Cons"]] <- findCuts(treeCons, globArr, obj, l+1, descL)
length(dCutsD[["gamma=5"]][["Cons"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cons", Value = val,
                  nCuts = length(dCutsD[["gamma=5"]][["Cons"]]), gamma=gamma))
save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData")
gc()

globArr <- rep(-100, l+treeMeanInf0$Nnode)
descL <- sapply(Descendants(treeMeanInf0, seq(l+treeMeanInf0$Nnode)), length)
obj <- mcols(yAggMeanInfNS0)[["meanInfRV"]] + gamma*node.depth(treeMeanInf0,2)
val <- findOptSum(treeMeanInf0, obj, l+1, descL)
dCutsD[["gamma=5"]][["MeanInf0"]] <- findCuts(treeMeanInf0, globArr, obj, l+1, descL)
length(dCutsD[["gamma=5"]][["MeanInf0"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf0", Value = val,
                 nCuts = length(dCutsD[["gamma=5"]][["MeanInf0"]]), gamma=gamma))
save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData")
gc()

globArr <- rep(-100, l+treeMeanInf$Nnode)
descL <- sapply(Descendants(treeMeanInf, seq(l+treeMeanInf$Nnode)), length)
obj <- mcols(yAggMeanInfNS)[["meanInfRV"]]  + gamma*node.depth(treeMeanInf,2)
val <- findOptSum(treeMeanInf, obj, l+1, descL)
dCutsD[["gamma=5"]][["MeanInf"]] <- findCuts(treeMeanInf, globArr, obj, l+1, descL)
length(dCutsD[["gamma=5"]][["MeanInf"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf", Value = val,
           nCuts = length(dCutsD[["gamma=5"]][["MeanInf"]]), gamma=gamma))
save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData")
gc()

globArr <- rep(-100, l+treeCor$Nnode)
descL <- sapply(Descendants(treeCor, seq(l+treeCor$Nnode)), length)
obj <- mcols(yAggCorNS)[["meanInfRV"]]  + gamma*node.depth(treeCor,2)
val <- findOptSum(treeCor, obj, l+1, descL)
dCutsD[["gamma=5"]][["Cor"]] <- findCuts(treeCor, globArr, obj, l+1, descL)
length(dCutsD[["gamma=5"]][["Cor"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cor", Value = val,
                 nCuts = length(dCutsD[["gamma=5"]][["Cor"]]), gamma=gamma))
gc()
save(dCutsD, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/mean_cons/cutsDepth.RData")
print(dfDepth)
```