---
title: "treeClimbR Results"
author: "Noor Pratap Singh"
date: "6/14/2021"
output: html_document
---

```{r}
source("tree_helper_function.R")
source("bouth_helper.R")
library(phangorn)
load("../mikelove-swimdown-216a1dd/simulate/data/simulate.rda")
load("environment/ygroup.RData")
load("environment/tree_group.RData")
missingTxps <- setdiff(rownames(y), rownames(sim.counts.mat))
sim.counts.mat <- rbind(sim.counts.mat, matrix(0, nrow = length(missingTxps), ncol = ncol(sim.counts.mat),
                                               dimnames = list(missingTxps, colnames(sim.counts.mat))))
sim.counts.mat <- sim.counts.mat[rownames(y),] ###Arranging in the manner of y

innNodes <- nrow(y)+1:tree$Nnode

aggCountsNodes <- computeAggNodes(tree, c(1:nrow(y),innNodes), sim.counts.mat)
fold_changes <- rbind(fold_changes, matrix(0, nrow = length(missingTxps), ncol = ncol(fold_changes),
                                               dimnames = list(missingTxps, colnames(fold_changes))))
logFCNodes <- ifelse(rowSums(aggCountsNodes)==0, 0, log2(aggCountsNodes[,2]/aggCountsNodes[,1]))
fold_changes <- fold_changes[rownames(y),]

trueCountNodes <- which(abs(logFCNodes) >= 0.066) ##Making sure root is non differentiated
trueLeaves <- union(trueCountNodes[trueCountNodes <= nrow(y)],unlist(Descendants(tree,trueCountNodes[trueCountNodes > nrow(y)])))
```

#### Swish on All
```{r}
load("environment/innNodes/bestSwish.RData")
detNodes <- sapply(bestSwish, function(sw) sw$output[sw$output$signal.node, "node"])
stats <-  sapply(detNodes, function(nodes) computeTPFP(trueCountNodes, nodes, y, NULL, tree, pTab=T, type="leaf"))
print(stats)
```

#### Swish on infRV
```{r}
load("environment/innNodes/bestSwInf.RData")
detNodes <- sapply(bestSwInf, function(sw) sw$output[sw$output$signal.node, "node"])
stats <-  sapply(detNodes, function(nodes) computeTPFP(trueCountNodes, nodes, y, NULL, tree, pTab=T, type="leaf"))
print(stats)
```

#### Just Swish on leaves
```{r}
load("environment/innNodes/ySwish.RData")
detNodes <- lapply(c(0.01,0.05,0.1), function(x) which(mcols(y)[,"qvalue"] <= x))
stats <-  sapply(detNodes, function(nodes) computeTPFP(trueCountNodes, nodes, y, NULL, tree, pTab=T, type="leaf"))
print(stats)
```

#### Just Swish on nodes
```{r}
detNodes <- lapply(c(0.01,0.05,0.1), function(x) which(mcols(yAll)[,"qvalue"] <= x))
stats <-  sapply(detNodes, function(nodes) computeTPFP(trueCountNodes, nodes, yAll, NULL, tree, pTab=T, type="leaf"))
print(stats)
```

#### Deseq2 on All
```{r}
load("environment/innNodes/bestDESeq2.RData")
detNodes <- sapply(bestDeseq2, function(de) de$output[de$output$signal.node, "node"])
stats <-  sapply(detNodes, function(nodes) computeTPFP(trueCountNodes, nodes, y, NULL, tree, pTab=T, type="leaf"))
print(stats)
```

#### Deseq2 on infRV
```{r}
load("environment/innNodes/best_deseq2_infRV.RData")
detNodes <- sapply(bestDeInf, function(de) de$output[de$output$signal.node, "node"])
stats <-  sapply(detNodes, function(nodes) computeTPFP(trueCountNodes, nodes, y, NULL, tree, pTab=T, type="leaf"))
print(stats)
```


<!-- #### Deseq2 on leaves -->
<!-- ```{r} -->
<!-- load("environment/innNodes/res.RData") -->
<!-- detNodes <- lapply(c(0.01,0.05,0.1), function(x) which(res$padj <= x)) -->
<!-- stats <-  sapply(detNodes, function(nodes) computeTPFP(trueCountNodes, nodes, y, NULL, tree, pTab=T, type="leaf")) -->
<!-- print(stats) -->
<!-- ``` -->
