```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

```{r}
load("environment/Chimp/mapDf.RData")
save_dir <- "environment/Chimp/mode=gcbias/post_type=gibbs_nrep=100_tf=100/tree_analysis"
load(file.path(save_dir, "treeCons.RData"))
load(file.path(save_dir, "treeCons0.RData"))
load(file.path(save_dir, "treeCor.RData"))
load(file.path(save_dir, "treeMeanInf0.RData"))
load(file.path(save_dir, "treeThr.RData"))
load(file.path(save_dir, "yAggConsNS.RData"))
load(file.path(save_dir, "yAggConsNS0.RData"))
load(file.path(save_dir, "yAggCorNS.RData"))
load(file.path(save_dir, "yAggMeanInfNS0.RData"))
load(file.path(save_dir, "yAggThrNS.RData"))
suppressPackageStartupMessages(source("tree_helper_function.R"))
suppressPackageStartupMessages(source("brain_simulation_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/tree_analysis/tree_filter.R"))

```

#### Gamma 0.1
```{r}
gamma <- 0.1
dfDepth <- data.frame(matrix(nrow=0, ncol=4))
dCutsD <- list()
dCutsD[["gamma=0.1"]] <- list()
colnames(dfDepth) <- c("Type", "Value", "nCuts", "gamma")
l <- length(treeCons0$tip)

globArr <- rep(-100, l+treeCons0$Nnode)
descL <- sapply(Descendants(treeCons0, seq(l+treeCons0$Nnode)), length)
obj <- mcols(yAggConsNS0)[["meanInfRV"]] + gamma*node.depth(treeCons0,2)
val <- findOptSum(treeCons0, obj, l+1, descL)
gc()
dCutsD[["gamma=0.1"]][["Cons0"]] <- findCuts(treeCons0, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=0.1"]][["Cons0"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cons0", Value = val,
       nCuts = length(dCutsD[["gamma=0.1"]][["Cons0"]]), gamma=gamma))

save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))


globArr <- rep(-100, l+treeCons$Nnode)
descL <- sapply(Descendants(treeCons, seq(l+treeCons$Nnode)), length)
obj <- mcols(yAggConsNS)[["meanInfRV"]] + gamma*node.depth(treeCons,2)
val <- findOptSum(treeCons, obj, l+1, descL)
gc()
dCutsD[["gamma=0.1"]][["Cons"]] <- findCuts(treeCons, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=0.1"]][["Cons"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cons", Value = val,
                  nCuts = length(dCutsD[["gamma=0.1"]][["Cons"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeMeanInf0$Nnode)
descL <- sapply(Descendants(treeMeanInf0, seq(l+treeMeanInf0$Nnode)), length)
obj <- mcols(yAggMeanInfNS0)[["meanInfRV"]] + gamma*node.depth(treeMeanInf0,2)
gc()
val <- findOptSum(treeMeanInf0, obj, l+1, descL)
gc()
dCutsD[["gamma=0.1"]][["MeanInf0"]] <- findCuts(treeMeanInf0, globArr, obj, l+1, descL)
length(dCutsD[["gamma=0.1"]][["MeanInf0"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf0", Value = val,
                 nCuts = length(dCutsD[["gamma=0.1"]][["MeanInf0"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))
gc()

globArr <- rep(-100, l+treeCor$Nnode)
descL <- sapply(Descendants(treeCor, seq(l+treeCor$Nnode)), length)
obj <- mcols(yAggCorNS)[["meanInfRV"]]  + gamma*node.depth(treeCor,2)
gc()
val <- findOptSum(treeCor, obj, l+1, descL)
gc()
dCutsD[["gamma=0.1"]][["Cor"]] <- findCuts(treeCor, globArr, obj, l+1, descL)
length(dCutsD[["gamma=0.1"]][["Cor"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cor", Value = val,
                 nCuts = length(dCutsD[["gamma=0.1"]][["Cor"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeThr$Nnode)
descL <- sapply(Descendants(treeThr, seq(l+treeThr$Nnode)), length)
obj <- mcols(yAggThrNS)[["meanInfRV"]]  + gamma*node.depth(treeThr,2)
gc()
val <- findOptSum(treeThr, obj, l+1, descL)
gc()
dCutsD[["gamma=0.1"]][["Thr"]] <- findCuts(treeCor, globArr, obj, l+1, descL)
length(dCutsD[["gamma=0.1"]][["Thr"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "ConsThr", Value = val,
                 nCuts = length(dCutsD[["gamma=0.1"]][["Thr"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))
print(dfDepth)
```

#### Gamma 0.5
```{r}
gamma <- 0.5
dCutsD[["gamma=0.5"]] <- list()

globArr <- rep(-100, l+treeCons0$Nnode)
descL <- sapply(Descendants(treeCons0, seq(l+treeCons0$Nnode)), length)
obj <- mcols(yAggConsNS0)[["meanInfRV"]] + gamma*node.depth(treeCons0,2)
val <- findOptSum(treeCons0, obj, l+1, descL)
gc()
dCutsD[["gamma=0.5"]][["Cons0"]] <- findCuts(treeCons0, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=0.5"]][["Cons0"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cons0", Value = val,
       nCuts = length(dCutsD[["gamma=0.5"]][["Cons0"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeCons$Nnode)
descL <- sapply(Descendants(treeCons, seq(l+treeCons$Nnode)), length)
obj <- mcols(yAggConsNS)[["meanInfRV"]] + gamma*node.depth(treeCons,2)
val <- findOptSum(treeCons, obj, l+1, descL)
gc()
dCutsD[["gamma=0.5"]][["Cons"]] <- findCuts(treeCons, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=0.5"]][["Cons"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cons", Value = val,
                  nCuts = length(dCutsD[["gamma=0.5"]][["Cons"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeMeanInf0$Nnode)
descL <- sapply(Descendants(treeMeanInf0, seq(l+treeMeanInf0$Nnode)), length)
obj <- mcols(yAggMeanInfNS0)[["meanInfRV"]] + gamma*node.depth(treeMeanInf0,2)
val <- findOptSum(treeMeanInf0, obj, l+1, descL)
gc()
dCutsD[["gamma=0.5"]][["MeanInf0"]] <- findCuts(treeMeanInf0, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=0.5"]][["MeanInf0"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf0", Value = val,
                 nCuts = length(dCutsD[["gamma=0.5"]][["MeanInf0"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeCor$Nnode)
descL <- sapply(Descendants(treeCor, seq(l+treeCor$Nnode)), length)
obj <- mcols(yAggCorNS)[["meanInfRV"]]  + gamma*node.depth(treeCor,2)
val <- findOptSum(treeCor, obj, l+1, descL)
gc()
dCutsD[["gamma=0.5"]][["Cor"]] <- findCuts(treeCor, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=0.5"]][["Cor"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cor", Value = val,
                 nCuts = length(dCutsD[["gamma=0.5"]][["Cor"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeThr$Nnode)
descL <- sapply(Descendants(treeThr, seq(l+treeThr$Nnode)), length)
obj <- mcols(yAggThrNS)[["meanInfRV"]]  + gamma*node.depth(treeThr,2)
gc()
val <- findOptSum(treeThr, obj, l+1, descL)
gc()
dCutsD[["gamma=0.5"]][["Thr"]] <- findCuts(treeCor, globArr, obj, l+1, descL)
length(dCutsD[["gamma=0.5"]][["Thr"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "ConsThr", Value = val,
                 nCuts = length(dCutsD[["gamma=0.5"]][["Thr"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))
print(dfDepth)
```

#### Gamma 1
```{r}
gamma <- 1
dCutsD[["gamma=1"]] <- list()

globArr <- rep(-100, l+treeCons0$Nnode)
descL <- sapply(Descendants(treeCons0, seq(l+treeCons0$Nnode)), length)
obj <- mcols(yAggConsNS0)[["meanInfRV"]] + gamma*node.depth(treeCons0,2)
val <- findOptSum(treeCons0, obj, l+1, descL)
gc()
dCutsD[["gamma=1"]][["Cons0"]] <- findCuts(treeCons0, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma"]][["Cons0"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cons0", Value = val,
       nCuts = length(dCutsD[["gamma=1"]][["Cons0"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeCons$Nnode)
descL <- sapply(Descendants(treeCons, seq(l+treeCons$Nnode)), length)
obj <- mcols(yAggConsNS)[["meanInfRV"]] + gamma*node.depth(treeCons,2)
val <- findOptSum(treeCons, obj, l+1, descL)
gc()
dCutsD[["gamma=1"]][["Cons"]] <- findCuts(treeCons, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=1"]][["Cons"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cons", Value = val,
                  nCuts = length(dCutsD[["gamma=1"]][["Cons"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeMeanInf0$Nnode)
descL <- sapply(Descendants(treeMeanInf0, seq(l+treeMeanInf0$Nnode)), length)
obj <- mcols(yAggMeanInfNS0)[["meanInfRV"]] + gamma*node.depth(treeMeanInf0,2)
val <- findOptSum(treeMeanInf0, obj, l+1, descL)
gc()
dCutsD[["gamma=1"]][["MeanInf0"]] <- findCuts(treeMeanInf0, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=1"]][["MeanInf0"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf0", Value = val,
                 nCuts = length(dCutsD[["gamma=1"]][["MeanInf0"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeCor$Nnode)
descL <- sapply(Descendants(treeCor, seq(l+treeCor$Nnode)), length)
obj <- mcols(yAggCorNS)[["meanInfRV"]]  + gamma*node.depth(treeCor,2)
val <- findOptSum(treeCor, obj, l+1, descL)
gc()
dCutsD[["gamma=1"]][["Cor"]] <- findCuts(treeCor, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=1"]][["Cor"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cor", Value = val,
                 nCuts = length(dCutsD[["gamma=1"]][["Cor"]]), gamma=gamma))

globArr <- rep(-100, l+treeThr$Nnode)
descL <- sapply(Descendants(treeThr, seq(l+treeThr$Nnode)), length)
obj <- mcols(yAggThrNS)[["meanInfRV"]]  + gamma*node.depth(treeThr,2)
gc()
val <- findOptSum(treeThr, obj, l+1, descL)
gc()
dCutsD[["gamma=1"]][["Thr"]] <- findCuts(treeCor, globArr, obj, l+1, descL)
length(dCutsD[["gamma=1"]][["Thr"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "ConsThr", Value = val,
                 nCuts = length(dCutsD[["gamma=1"]][["Thr"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))
print(dfDepth)
```

#### Gamma 5
```{r}
gamma <- 5
dCutsD[["gamma=5"]] <- list()

globArr <- rep(-100, l+treeCons0$Nnode)
descL <- sapply(Descendants(treeCons0, seq(l+treeCons0$Nnode)), length)
obj <- mcols(yAggConsNS0)[["meanInfRV"]] + gamma*node.depth(treeCons0,2)
val <- findOptSum(treeCons0, obj, l+1, descL)
gc()
dCutsD[["gamma=5"]][["Cons0"]] <- findCuts(treeCons0, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=5"]][["Cons0"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cons0", Value = val,
       nCuts = length(dCutsD[["gamma=5"]][["Cons0"]]), gamma=gamma))

save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeCons$Nnode)
descL <- sapply(Descendants(treeCons, seq(l+treeCons$Nnode)), length)
obj <- mcols(yAggConsNS)[["meanInfRV"]] + gamma*node.depth(treeCons,2)
val <- findOptSum(treeCons, obj, l+1, descL)
gc()
dCutsD[["gamma=5"]][["Cons"]] <- findCuts(treeCons, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=5"]][["Cons"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cons", Value = val,
                  nCuts = length(dCutsD[["gamma=5"]][["Cons"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeMeanInf0$Nnode)
descL <- sapply(Descendants(treeMeanInf0, seq(l+treeMeanInf0$Nnode)), length)
obj <- mcols(yAggMeanInfNS0)[["meanInfRV"]] + gamma*node.depth(treeMeanInf0,2)
val <- findOptSum(treeMeanInf0, obj, l+1, descL)
gc()
dCutsD[["gamma=5"]][["MeanInf0"]] <- findCuts(treeMeanInf0, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=5"]][["MeanInf0"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "MeanInf0", Value = val,
                 nCuts = length(dCutsD[["gamma=5"]][["MeanInf0"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeCor$Nnode)
descL <- sapply(Descendants(treeCor, seq(l+treeCor$Nnode)), length)
obj <- mcols(yAggCorNS)[["meanInfRV"]]  + gamma*node.depth(treeCor,2)
val <- findOptSum(treeCor, obj, l+1, descL)
gc()
dCutsD[["gamma=5"]][["Cor"]] <- findCuts(treeCor, globArr, obj, l+1, descL)
gc()
length(dCutsD[["gamma=5"]][["Cor"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "Cor", Value = val,
                 nCuts = length(dCutsD[["gamma=5"]][["Cor"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

globArr <- rep(-100, l+treeThr$Nnode)
descL <- sapply(Descendants(treeThr, seq(l+treeThr$Nnode)), length)
obj <- mcols(yAggThrNS)[["meanInfRV"]]  + gamma*node.depth(treeThr,2)
gc()
val <- findOptSum(treeThr, obj, l+1, descL)
gc()
dCutsD[["gamma=5"]][["Thr"]] <- findCuts(treeCor, globArr, obj, l+1, descL)
length(dCutsD[["gamma=5"]][["Thr"]])
dfDepth <- rbind(dfDepth, data.frame(Type = "ConsThr", Value = val,
                 nCuts = length(dCutsD[["gamma=5"]][["Thr"]]), gamma=gamma))
save(dCutsD, file=file.path(save_dir, "cutsDepth.RData"))

print(dfDepth)
```