---
title: "Run BOUTH"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

```{r}
suppressPackageStartupMessages(library(BOUTH))
suppressPackageStartupMessages(library(SummarizedExperiment))
suppressPackageStartupMessages(library(beaveR))
suppressPackageStartupMessages(source("tree_helper_function.R"))

quantDir <- "/fs/cbcb-scratch/jfan03/treeterm-paper/output/seed=1_fc=2:6/post_type=gibbs_nrep=100_tf=100/salmon_quants"
saveDir <- "environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees_updated_sim"
samples <- as.vector(outer(c(1:6), c(1,2), function(x,y) paste(x,y,sep="_")))
files <- file.path(quantDir, samples, "quant.sf")
coldata <- data.frame(files = files, names = samples, condition = as.factor(rep(c(1,2),each=6)))
clustFile <- "/fs/cbcb-scratch/jfan03/treeterm-paper/output/seed=1_fc=2:6/post_type=gibbs_nrep=100_tf=100/terminus/no_threshold0/cluster_nwk.txt"

tseCons <- buildTSE(treeTermFile = clustFile, coldata = coldata)
treeCons <- rowTree(tseCons)
l <- length(treeCons$tip)
```

```{r}
y <- fishpond::scaleInfReps(tseCons[1:l,])
y <- labelKeep(y)
mcols(y)[["keep"]] <- T
set.seed(10)
y <- swish(y, x="condition")

bouthTree <- getTreeDf(treeCons)
save(bouthTree, file=file.path(saveDir, "bouthTreeCons.RData"))
pvalues <- mcols(y)[["pvalue"]]
bouthBrain <- list()
print(system.time(bouthBrain[['0.01']] <- bouth(anno.table = bouthTree, pvalue.leaves = pvalues, na.symbol = "unknown", far = 0.01, is.weighted = TRUE)))
save(bouthBrain, file = file.path(saveDir, "bouthBrain.RData"))
print(system.time(bouthBrain[['0.05']] <- bouth(anno.table = bouthTree, pvalue.leaves = pvalues, na.symbol = "unknown", far = 0.05, is.weighted = TRUE)))
save(bouthBrain, file = file.path(saveDir, "bouthBrain.RData"))
print(system.time(bouthBrain[['0.1']] <- bouth(anno.table = bouthTree, pvalue.leaves = pvalues, na.symbol = "unknown", far = 0.1, is.weighted = TRUE)))
save(bouthBrain, file = file.path(saveDir, "bouthBrain.RData"))
```
