---
title: "Correlation Trees"
author: "Noor Pratap Singh"
date: "4/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

```{r}
suppressPackageStartupMessages(library(SummarizedExperiment))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(ape))
suppressPackageStartupMessages(library(phangorn))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(HDF5Array))
suppressPackageStartupMessages(library(BiocParallel))
suppressPackageStartupMessages(source("tree_helper_function.R"))
# load("environment/real_datasets/GSE100505/mode_gcbias=True/posttype=gibbs_npost=100_tf=100/seMuscle.RData")
load("environment/real_datasets/GSE100505/mapDf.RData")
```

```{r}
UPGMA <- function (D, method = "average", ...) 
{
    DD <- as.dist(D)
    hc <- fastcluster::hclust(DD, method = method, ...)
    result <- as.phylo(hc)
    result <- reorder(result, "postorder")
    result
}
```

#### Creating anti-correlation trees
```{r}
# seNorm <- scaleInfReps(seMuscle)
# infReps <- assays(seMuscle)[grep("infRep", assayNames(seMuscle))]
# infReps <- abind::abind(as.list(infReps), along = 3)
# tInds <- lapply(seq(12), function(i) which(rowSums(infReps[,i,]) == 0))
# rInds <- which(rowSums(assays(seMuscle)[["counts"]]) == 0)
# tInds <- Reduce(union,tInds)
# rInds <- union(rInds, tInds)
# infReps <- assays(seNorm)[grep("infRep", assayNames(seNorm))]
# infReps <- abind::abind(as.list(infReps), along = 3)
# tInds <- lapply(seq(12), function(i) which(rowSums(infReps[,i,]) == 0))
# tInds <- Reduce(union,tInds)
# rInds <- union(rInds, tInds)
# infReps <- infReps[-tInds,,]
# trCorUPGMA <- list()
#  
# corMats <- list()
# corMean <- matrix(0, dim(infReps)[1], dim(infReps)[1])
# for(i in seq(12)) {
#      corTxps <- cor(t(infReps[,i,]))
#      ###Building on anticorrelation
#      corMean <- corMean + corTxps
#      rm(corTxps)
#      gc()
# }
# corMean <- corMean/12
# print(head(corMean))
# save(corMean, file = "environment/real_datasets/GSE100505/mode_gcbias=True/posttype=gibbs_npost=100_tf=100/comp_trees/cor_mean.RData")
load("environment/real_datasets/GSE100505/mode_gcbias=True/posttype=gibbs_npost=100_tf=100/comp_trees/cor_mean.RData")
d <- (1+corMean)/2
trMeanCorUPGMANorm <- UPGMA(d)
save(trMeanCorUPGMANorm, file="environment/real_datasets/GSE100505/mode_gcbias=True/posttype=gibbs_npost=100_tf=100/comp_trees/trMeanCorUPGMANorm.RData")
trMeanCorUPGMANorm$tip.label <- rownames(corMean)
save(trMeanCorUPGMANorm, file="environment/real_datasets/GSE100505/mode_gcbias=True/posttype=gibbs_npost=100_tf=100/comp_trees/trMeanCorUPGMANorm.RData")
```