---
title: "Comp Different trees"
author: "Noor Pratap Singh"
date: "5/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

```{r}
suppressPackageStartupMessages(library(SummarizedExperiment))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(ape))
suppressPackageStartupMessages(library(phangorn))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(source("tree_helper_function.R"))
suppressPackageStartupMessages(source("brain_simulation_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/tree_analysis/tree_filter.R"))

load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/tree.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/mapDf.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/updated/yAgg.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/y.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/trMeanCor.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/yCorMeanAgg.RData")
```

#### Building infRV data frame
```{r}
# depth <- node.depth(tree,2)
# modDep <- depth
# modDep[depth >=7] = 7
# 
# dfInfRV <- data.frame(infRV = mcols(yAll)[["meanInfRV"]], depth = depth, modDep = modDep, type = "Consensus")
# 
# ### Correlation trees
# depth <- node.depth(trMeanCor,2)
# modDep <- depth
# modDep[depth >=7] = 7
# dfInfRV <- rbind(dfInfRV, data.frame(infRV = mcols(yCorMeanAgg)[["meanInfRV"]], depth = depth, modDep = modDep, type = "Correlation"))
# # 
# ### Random tree
# for(i in seq(20)) {
#     tr <- tree
#     depth <- node.depth(tr,2)
#     yR <- y
#     modDep <- depth
#     modDep[depth >=7] = 7
#     tr$tip.label <- sample(tree$tip.label)
#     yR <- yR[tr$tip,]
#     yAgg <- prepSwish(tr, yR)
#     
#     yAgg <- fishpond::computeInfRV(yAgg, meanVariance=F)
#     dfInfRV <- rbind(dfInfRV, data.frame(infRV = mcols(yAgg)[["meanInfRV"]], depth = depth, modDep = modDep, type = "Random"))
# }
# save(dfInfRV, file="environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/dfInfRV.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/dfInfRV.RData")

### Level Wise comparison
ggplot(dfInfRV, aes(x=factor(type), y=log10(infRV))) + geom_violin() + facet_wrap(vars(modDep))

for(i in seq_along(7)) {
    dfR <- dfInfRV[dfInfRV$modDep==i,]
    ggplot(dfR, aes(x=log10(infRV))) + geom_histogram() + facet_wrap(vars(type))
}
```


```{r}
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/infRVTree.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/trMS.RData")
infRVSamp <- computeInfRV(yAll)[["InfRV"]]
dfInfCons <- data.frame(matrix(ncol=4, nrow=0))
colnames(dfInfCons) <- c("infRV", "sample", "depth", "type")
depth <- node.depth(tree, 2)
depth[depth > 6] = 7
### Consensus Tree
dfInfCons <- rbind(dfInfCons, data.frame(infRV = rowMeans(infRVSamp), sample="all", depth = depth, type = "meanCons"))
### Consensus tree across samples
for(i in seq(12)) {
    dfInfCons <- rbind(dfInfCons, data.frame(infRV = infRVSamp[,i], sample=colnames(infRVSamp)[i], depth = depth, type = "consInd"))
}

### Individual tree across samples
for(i in seq(12)) {
    depth <- node.depth(trMS[[i]], 2)
    depth[depth > 6] = 7
    dfInfCons <- rbind(dfInfCons, data.frame(infRV = infRVs[[i]][,1], sample=colnames(infRVSamp)[i], depth = depth, type = "treeInd"))
}

ggplot(dfInfCons, aes(x=factor(type), y=log10(infRV))) + geom_violin() + facet_wrap(vars(depth))

for(i in seq(7)) {
    dfR <- dfInfCons[dfInfCons[["depth"]]==i,]
    print(ggplot(dfR, aes(x=log10(infRV))) + geom_histogram() + facet_wrap(vars(factor(type))))
}
```
