---
title: "Checking Quality of Consensus"
author: "Noor Pratap Singh"
date: "4/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

#### Loading Packages
```{r}
suppressPackageStartupMessages(library(fishpond))
suppressPackageStartupMessages(library(SummarizedExperiment))
suppressPackageStartupMessages(library(phangorn))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(reshape))
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/tree.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/mapDf.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/yAll.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/y.RData")

computeInfRV <- function (y, pc = 5, shift = 0.01, rMean=F) 
{
    infReps <- assays(y)[grep("infRep", assayNames(y))]
    infReps <- abind::abind(as.list(infReps), along = 3)
    infMean <- apply(infReps, 1:2, mean)
    infVar <- apply(infReps, 1:2, var)
    assays(y)[["mean"]] <- infMean
    assays(y)[["variance"]] <- infVar
    
    InfRV <- pmax(infVar - infMean, 0)/(infMean + pc) + shift
    if(rMean)
        return(rowMeans(InfRV))
    return(InfRV)
}

```

#### Plotting distribution of InfRV  (Mean and Variance) across replicates stratified by depth
```{r}
infRVSamp <- computeInfRV(yAll)
infRVSampMean <- rowMeans(infRVSamp)
infRVSampVar <- rowVars(infRVSamp)
depth <- node.depth(tree,2)
modDep <- depth
modDep[depth >=7] = 7

dfMean <- data.frame(mean=infRVSampMean, var=infRVSampVar, depth = depth, modDep = depth) 
dfMean[["modDep"]][dfMean[["modDep"]] > 6] = 7

pL <- list()
### Plotting mean of infRV across replicates
for(i in seq(7)) {
    dfR <- dfMean[dfMean[["modDep"]] == i, ]
    pL[[i]] <- ggplot(dfR, aes(x=log10(mean))) +  geom_histogram()     #+facet_wrap(vars(modDep)) 
}
ggarrange(plotlist=pL)

### Plotting variance of infRV across replicates
pL <- list()
for(i in seq(7)) {
    dfR <- dfMean[dfMean[["modDep"]] == i, ]
    pL[[i]] <- ggplot(dfR, aes(x=log10(var))) +  geom_histogram()     #+facet_wrap(vars(modDep)) 
}
ggarrange(plotlist=pL)

### Plotting variance with uncertainty
pL <- list()
for(i in seq(7)) {
    dfR <- dfMean[dfMean[["modDep"]] == i, ]
    pL[[i]] <- ggplot(dfR, aes(x=log10(mean),y=log10(var))) +  geom_hex()     #+facet_wrap(vars(modDep)) 
}
ggarrange(plotlist=pL)

```


#### Sample level inferential uncertainty stratified by depth
```{r}
dfComb <- melt(infRVSamp, value.name = "infRV")
dfComb <- cbind(dfComb, modDep = rep(modDep, 12))
colnames(dfComb)[3] <- "infRV"
pL <- list()
ggplot(dfComb, aes(x=log10(infRV))) + geom_histogram() + facet_wrap(vars(modDep))
ggplot(dfComb, aes(x=factor(modDep), y=log10(infRV))) +  geom_violin()
```

<!-- #### Extract sample level trees -->
<!-- ```{r} -->
<!-- termDir <- "/fs/cbcb-lab/rob/students/noor/Uncertainity/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/out_term_temp" -->
<!-- samples <- as.vector(outer(c(1:6), c(1,2), function(x,y) paste(x,y,sep="_"))) -->
<!-- sampTFiles <- paste(termDir, samples, "group_nwk.txt",sep="/") -->

<!-- trS <- lapply(sampTFiles, function(file) read.tree(file = file)) -->
<!-- trMS <- list() ##Merged trees  -->
<!-- infRVs <- mclapply(seq(12), function(i) { -->
<!--     tr <- trS[[i]] -->
<!--     trMS[[i]] <- mergeTree(tr, se=mapDf) -->
<!--     yR <- y -->
<!--     yR <- yR[tr$tip,i] -->
<!--     yAgg <- prepSwish(tr, yR) -->
<!--     infRV <- computeInfRV(yAgg[,1], rMean=F) -->
<!--     }, mc.cores=4) -->
<!-- save(infRVs, file = "environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/infRVTree.RData") -->
<!-- save(trMS, file = "environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/trMS.RData") -->

<!-- depthTr <- lapply(trMS, function(tr) node.depth(tr, 2)) -->
<!-- depthTr <- lapply(depthTr, function(dep) { -->
<!--     dep[dep >=7] <- 7 -->
<!--     dep -->
<!-- }) -->
<!-- dfIndSamp <- data.frame(matrix(ncol=3, nrow=0)) -->
<!-- colnames(dfIndSamp) <- c("infRV", "sample", "depth") -->
<!-- for(i in seq(12)) { -->
<!--     df <- data.frame(infRV = infRVs[[i]][,1], sample = rep(samples[i],length(infRVs[[i]])), depth = depthTr[[i]]) -->
<!--     dfIndSamp <- rbind(dfIndSamp, df) -->
<!-- } -->

<!-- ggplot(dfIndSamp, aes(x = factor(depth), y=log10(infRV))) + geom_violin() -->
<!-- ``` -->

#### NGenes
```{r}
nNodes <- nrow(y)+tree$Nnode
desc <- Descendants(tree, seq(nNodes))
genesL <- mclapply(desc[nrow(y)+1:tree$Nnode], function(txps) unique(mapDf[rownames(y)[txps],1]), mc.cores=4)
nGenes <- rep(0, nNodes)
nGenes[1:nrow(y)] <- 1
nGenes[nrow(y)+1:tree$Nnode] <- sapply(genesL, length)

depth <- node.depth(tree,2)
modDep <- depth
modDep[depth >=7] = 7

df <- data.frame(nGenes = nGenes, modDep = modDep, depth=depth)
pL <- list()
for(i in seq(7)) {
    dfR <- df[df[["modDep"]] == i, ]
    if(i==7) {
        print(sum(dfR[["nGenes"]] > 100))
        dfR <- dfR[dfR[["nGenes"]] <= 100,]
    }
        
    pL[[i]] <- ggplot(dfR, aes(x=nGenes)) +  geom_histogram()     #+facet_wrap(vars(modDep)) 
}
ggarrange(plotlist=pL)
```

#### Gene Families
```{r}
library(biomaRt)
ensembl <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")

rGenes <- genesL[sapply(genesL, length)==58][[1]]
rGenes <- gsub("\\.[0-9]+", "", rGenes)
print(getBM(attributes=c("ensembl_gene_id", "hgnc_symbol", "description"), filters="ensembl_gene_id", values=rGenes, mart=ensembl))

rGenes <- genesL[sapply(genesL, length)==35][[1]]
rGenes <- gsub("\\.[0-9]+", "", rGenes)
print(getBM(attributes=c("ensembl_gene_id", "hgnc_symbol", "description"), filters="ensembl_gene_id", values=rGenes, mart=ensembl))

rGenes <- genesL[sapply(genesL, length)==25][[1]]
rGenes <- gsub("\\.[0-9]+", "", rGenes)
print(getBM(attributes=c("ensembl_gene_id", "hgnc_symbol", "description"), filters="ensembl_gene_id", values=rGenes, mart=ensembl))

rGenes <- genesL[sapply(genesL, length)==23][[1]]
rGenes <- gsub("\\.[0-9]+", "", rGenes)
print(getBM(attributes=c("ensembl_gene_id", "hgnc_symbol", "description"), filters="ensembl_gene_id", values=rGenes, mart=ensembl))
```