---
title: "Comp Different trees"
author: "Noor Pratap Singh"
date: "5/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

```{r}
suppressPackageStartupMessages(library(SummarizedExperiment))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(ape))
suppressPackageStartupMessages(library(phangorn))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggpubr))

load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/tree.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/mapDf.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/yAll.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/y.RData")
# load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/trUpgma.RData")
# load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/yM.RData")
# load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/yA.RData")

suppressPackageStartupMessages(source("tree_helper_function.R"))

computeInfRV <- function (y, pc = 5, shift = 0.01, rMean=F) 
{
    infReps <- assays(y)[grep("infRep", assayNames(y))]
    infReps <- abind::abind(as.list(infReps), along = 3)
    infMean <- apply(infReps, 1:2, mean)
    infVar <- apply(infReps, 1:2, var)
    assays(y)[["mean"]] <- infMean
    assays(y)[["variance"]] <- infVar
    
    InfRV <- pmax(infVar - infMean, 0)/(infMean + pc) + shift
    if(rMean)
        return(rowMeans(InfRV))
    return(InfRV)
}
```

#### Building infRV data frame
```{r}
infRVSamp <- computeInfRV(yAll)
# infRVSampMean <- rowMeans(infRVSamp)
# depth <- node.depth(tree,2)
# modDep <- depth
# modDep[depth >=7] = 7
# 
# dfInfRV <- data.frame(infRV = infRVSampMean, depth = depth, modDep = modDep, type = "Consensus")
# 
# ### Correlation trees
# infRVCorr <- computeInfRV(yA)
# depth <- node.depth(trUPGMA,2)
# modDep <- depth
# modDep[depth >=7] = 7
# dfInfRV <- rbind(dfInfRV, data.frame(infRV = rowMeans(infRVCorr), depth = depth, modDep = modDep, type = "Correlation"))
# 
# ### Random tree
# tr <- tree
# depth <- node.depth(tr,2)
# yR <- y
# modDep <- depth
# modDep[depth >=7] = 7
# tr$tip <- sample(tree$tip)
# yR <- yR[tr$tip,]
# yAgg <- prepSwish(tr, yR)
# 
# infRVMean <- computeInfRV(yAgg, rMean=T)
# dfInfRV <- rbind(dfInfRV, data.frame(infRV = infRVMean, depth = depth, modDep = modDep, type = "Random"))

### Level Wise comparison
# ggplot(dfInfRV, aes(x=factor(type), y=log10(infRV))) + geom_violin() + facet_wrap(vars(modDep))
```


```{r}
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/infRVTree.RData")
load("environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/trMS.RData")
dfInfCons <- data.frame(matrix(ncol=4, nrow=0))
colnames(dfInfCons) <- c("infRV", "sample", "depth", "type")
depth <- node.depth(tree, 2)
depth[depth > 6] = 7
### Consensus Tree
dfInfCons <- rbind(dfInfCons, data.frame(infRV = rowMeans(infRVSamp), sample="all", depth = depth, type = "meanCons"))
### Consensus tree across samples
for(i in seq(12)) {
    dfInfCons <- rbind(dfInfCons, data.frame(infRV = infRVSamp[,i], sample=colnames(infRVSamp)[i], depth = depth, type = "consInd"))
}

### Individual tree across samples
for(i in seq(12)) {
    depth <- node.depth(trMS[[i]], 2)
    depth[depth > 6] = 7
    dfInfCons <- rbind(dfInfCons, data.frame(infRV = infRVs[[i]][,1], sample=colnames(infRVSamp)[i], depth = depth, type = "treeInd"))
}

ggplot(dfInfCons, aes(x=factor(type), y=log10(infRV))) + geom_violin() + facet_wrap(vars(depth))

for(i in seq(7)) {
    dfR <- dfInfCons[dfInfCons[["depth"]]==i,]
    print(ggplot(dfR, aes(x=log10(infRV))) + geom_histogram() + facet_wrap(vars(factor(type))))
}
```
