```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

```{r}
suppressPackageStartupMessages(source("tree_helper_function.R"))
suppressPackageStartupMessages(source("tree_term_climb.R"))
load("environment/brain_sim_nodtu_lowfc/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/yAll.RData")
load("environment/brain_sim_nodtu_lowfc/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/y.RData")
load("environment/brain_sim_nodtu_lowfc/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/tree.RData")
load("environment/brain_sim_nodtu_lowfc/simulate.rda")
library(fdrtool)

load("environment/brain_sim_nodtu_lowfc/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/tAfterQvalue.RData")
```


```{r}
signs <- computeSign(yAll, "condition")
missingTxps <- setdiff(tree$tip, rownames(sim.counts.mat))
sim.counts.mat <- rbind(sim.counts.mat, matrix(0, nrow = length(missingTxps), ncol = ncol(sim.counts.mat),
                                               dimnames = list(missingTxps, colnames(sim.counts.mat))))
sim.counts.mat <- sim.counts.mat[tree$tip,]
length(missingTxps)

innNodes <- length(tree$tip)+1:tree$Nnode
aggCountsNodes <- computeAggNodesU(tree, c(1:length(tree$tip),innNodes), sim.counts.mat)

logFCNodes <- ifelse(rowSums(aggCountsNodes)==0, 0, log2(aggCountsNodes[,2]+1)-log2(aggCountsNodes[,1]+1))
iso.any <- iso.dtu | iso.dte | iso.dge
dts <- intersect(names(iso.any)[iso.any], names(logFCNodes))
rootFC <- abs(logFCNodes[length(tree$tip)+1])
dts <- setdiff(dts, dts[which(abs(logFCNodes[dts]) <= rootFC)])

print(mean(abs(logFCNodes[dts]) > rootFC))
```

```{r}
detNodes <- list()
pvalAdjL <- p.adjust(mcols(yAll)[["pvalue"]][1:nrow(y)], method="BH")
pvalsInn <- mcols(yAll)[["pvalue"]][nrow(y)+1:tree$Nnode]
naInds <- is.na(pvalsInn)
fdrIn <- fdrtool(pvalsInn[!naInds], statistic="pvalue")

pvalAdjIn <- rep(1, length(naInds))
pvalAdjIn[!naInds] <- fdrIn[["lfdr"]]
inCNodes <- lapply(c(0.01, 0.05, 0.1), function(alpha) which(pvalAdjIn < alpha))
inCNodes <- lapply(inCNodes, function(x) c(nrow(y)+1:tree$Nnode)[x])
inCNodes <- sapply(seq_along(inCNodes), function(i) intersect(tAfterQvalue[[i]][["candNodeO"]], inCNodes[[i]]))

detNodes[["tAfterlFDR"]] <- lapply(c(0.01, 0.05, 0.1), function(alpha) which(pvalAdjL < alpha)) ## All leaf nodes
detNodes[["tAfterlFDR"]] <- lapply(seq(3), function(i) c(detNodes[["tAfterlFDR"]][[i]], inCNodes[[i]]))
print(sapply(detNodes$treeClimbR, function(x) sum(x>nrow(y))))

iNodes <- detNodes[[1]][[3]][detNodes[[1]][[3]] > nrow(y)]
mean(abs(logFCNodes[iNodes]) > rootFC)

pthr <- estimatePThresh(yAll[1:nrow(y),], 0.1)
plfdr <- estimatePThresh(yAll[nrow(y)+1:tree$Nnode,], 0.1, "lfdr")
print(pthr)
print(plfdr)
```

#### Candidate nodes
```{r}
remCNodes <- setdiff(tAfterQvalue[[3]][["candNodeO"]], detNodes[["tAfterlFDR"]][[3]])
remCNodes <- remCNodes[remCNodes > nrow(y)]
Ancs <- Ancestors(tree, remCNodes, "all")
inds <- which(sapply(Ancs, function(anc) sum(mcols(yAll)[anc,"pvalue"] < plfdr) > 0))
remAnc <- sapply(Ancs[inds], function(nodes) nodes[which(mcols(yAll)[nodes,"pvalue"] < plfdr)[1]])

print(length(remAnc))
mean(abs(logFCNodes[remAnc]) > rootFC)

remAnc <- remAnc[sapply(Descendants(tree, remAnc, "all"), function(nodes) all(signs[nodes] >= 0) | all(signs[nodes] <= 0))]
print(length(remAnc))
print(mean(abs(logFCNodes[remAnc]) > rootFC))

remAnc <- remAnc[sapply(Descendants(tree, remAnc, "all"), function(nodes) all(mcols(yAll)[nodes, "meanInfRV"] > 0.4))]
```

#### Negative nodes
```{r}
negNodes <- tAfterQvalue[[3]][["negNodeO"]]
negNodes <- negNodes[which(mcols(yAll)[negNodes,"pvalue"] > pthr)]
#negNodes <- negNodes[negNodes > nrow(y)]
Anc <- Ancestors(tree, negNodes)
Anc <- Anc[sapply(Anc,length)!=1]
inds <- which(sapply(Anc, function(anc) sum(mcols(yAll)[anc,"pvalue"] < plfdr, na.rm=T) > 0))

rAnc <- sapply(Anc[inds], function(nodes) nodes[which(mcols(yAll)[nodes,"pvalue"] < plfdr)[1]])

rAnc <- unique(rAnc)
rAnc <- rAnc[sapply(Descendants(tree, rAnc, "all"), function(nodes) all(signs[nodes] >= 0) | all(signs[nodes] <= 0))]
rAnc <- rAnc[sapply(Descendants(tree, rAnc, "all"), function(nodes) all(mcols(yAll)[nodes, "meanInfRV"] > 0.4))]
desc <- Descendants(tree, rAnc, "all")
rAnc <- rAnc[sapply(desc, function(nodes) {
  nonNA <- nodes[!is.na(mcols(yAll)[nodes,"pvalue"])]
  inn <- nonNA[nonNA > nrow(y)]
  leaf <- nonNA[nonNA <= nrow(y)]
  length(nonNA)==0 | (all(mcols(yAll)[leaf, "pvalue"] > pthr) & (ifelse(length(inn) == 0, T, all(mcols(yAll)[leaf, "pvalue"] > plfdr))))
})]

print(mean(abs(logFCNodes[rAnc]) > rootFC))
```

```{r}
innNodes <- c(iNodes, rAnc, remAnc)
length(innNodes)
print(mean(abs(logFCNodes[innNodes]) < rootFC))
```