---
title: "DTU Analysis"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

#### Loading TSE experiment
```{r}
suppressPackageStartupMessages(source("tree_helper_function.R"))
suppressPackageStartupMessages(source("tree_term_climb.R"))
suppressPackageStartupMessages(library(beaveR))
saveDir <- "environment/brain_sim_nodtu_lowfc/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/DE"
load(file=file.path(saveDir, "tseCons.RData"))
```

#### Loading Terminus
```{r}
suppressPackageStartupMessages(source("old_terminus_helper.R"))
termDir <- "/fs/cbcb-lab/rob/students/noor/Uncertainity/brain_sim_nodtu_lowfc/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/terminus/"
tree <- rowTree(tse)
l <- length(tree$tip)

termGroupDf <- read.delim(file.path(termDir, "old", "1_1", "clusters.txt"), header=F)
termTxps <- unlist(sapply(strsplit(termGroupDf$V1, split = ",", fixed = T), function(x) x[2:length(x)]))

if(!all(termTxps %in% rownames(tse)[1:l])) {
    clustFile <- "/fs/cbcb-lab/rob/students/noor/Uncertainity/brain_sim_nodtu_lowfc/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/terminus/no_threshold0/cluster_nwk.txt"
    quantDir <- file.path("/fs/cbcb-lab/rob/students/noor/Uncertainity/brain_sim_nodtu_lowfc/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/out_sal") 
    samples <- as.vector(outer(c(1:6), c(1,2), function(x,y) paste(x,y,sep='_')))
    quantFiles <- file.path(quantDir, samples, 'quant.sf')
    coldata <- data.frame(files=quantFiles, names=samples, condition=factor(rep(1:2, each=6)))    
    txps <- c(rownames(tse)[1:l], unlist(termTxps))
    tse <- buildTSE(treeTermFile = clustFile, coldata = coldata)
    save(tse, file=file.path(saveDir, "tseCons.RData"))
}
tree <- rowTree(tse)
l <- length(tree$tip)
# groupsClust <- parseClustFile(file.path(termDir, "old", "1_1", "clusters.txt"), tse[1:l,])
# mInds <- seq(l + length(groupsClust))
# yAggTermThrNS <- prepOSwish(yTermThrNS, mInds, groupsClust)
# 
# rownames(yAggTermThrNS)[l+1:length(groupsClust)] <- paste("Node", as.character(l+1:length(groupsClust)),sep="")
# metadata(yAggTermThrNS)[["txpsAnn"]] <- rowData(yTermThrNS)
# yAggTermThrNS <- yAggTermThrNS[-unlist(groupsClust),]
# dim(yAggTermThrNS)
```

```{r}
# load("environment/brain_sim_nodtu_lowfc/simulate.rda")
# suppressPackageStartupMessages(library(TreeSummarizedExperiment))
# suppressPackageStartupMessages(library(ape))
# 
# missingTxps <- setdiff(rownames(tse)[1:l], rownames(sim.counts.mat))
# dts <- Reduce(union, c(names(iso.dge)[iso.dge], names(iso.dte)[iso.dte], names(iso.dte.only)[iso.dte.only], 
#                        names(iso.dtu)[iso.dtu]))
# dts <- intersect(dts, rownames(sim.counts.mat))
# sim.counts.mat <- rbind(sim.counts.mat, matrix(0, nrow = length(missingTxps), ncol = ncol(sim.counts.mat),
#                                                dimnames = list(missingTxps, colnames(sim.counts.mat))))
# sim.counts.mat <- sim.counts.mat[rownames(tse)[1:l],]
# dts <- intersect(dts, rownames(sim.counts.mat))
# 
# innNodes <- l+1:tree$Nnode
# aggCountsNodes <- computeAggNodesU(tree, c(1:length(tree$tip),innNodes), sim.counts.mat)
# logFCNodes <- ifelse(rowSums(aggCountsNodes)==0, 0, log2(aggCountsNodes[,2]+1)-log2(aggCountsNodes[,1]+1))
# names(logFCNodes)[(l+1):length(logFCNodes)] <- paste("Node", names(logFCNodes)[(l+1):length(logFCNodes)], sep="")
# rootFC <- abs(logFCNodes[l+1])

```

#### Swish on the entire dataset 
```{r}
yAll <- computeSizeFactors(tse)
yAll <- scaleInfReps(yAll)
yAll <- labelKeep(yAll)
set.seed(1)
yAll <- swish(yAll, x = "condition")
```

#### Distribution of signs and levels
```{r}
#mIRV_cut <- cut(mIRVDiff[nLeaf+1:tree$Nnode], breaks = quantile(mIRVDiff[nLeaf+1:tree$Nnode], 0:4/4), include.lowest = T)
#print(table(mIRV_cut))
#termThresh <- quantile(mIRVDiff[nLeaf+1:tree$Nnode], 0.75)
signs <- computeSign(yAll, "condition")
print(table(signs))
levels <- node.depth(tree, 2)
levels <- ifelse(levels > 4, 5, levels)
print(table(levels))
print(table(signs, levels))
```

#### Running 
```{r}
tAfterBHMoreClimbMIRV <- list() ## These are with mIRV criteria on child only
print(system.time(tAfterBHMoreClimbMIRV[["mIRV=0"]] <- mclapply(c(0.01, 0.05, 0.1), function(alpha) climbMax(yAll, tree, 0, alpha, cores=3), mc.cores=3)))
save(tAfterBHMoreClimbMIRV, file = file.path(saveDir, "tAfterBHMoreClimbMIRV.RData"))

print(system.time(tAfterBHMoreClimbMIRV[["mIRV=0.4"]] <- mclapply(c(0.01, 0.05, 0.1), function(alpha) climbMax(yAll, tree, 0.4, alpha, cores=3), mc.cores=3)))
save(tAfterBHMoreClimbMIRV, file = file.path(saveDir, "tAfterBHMoreClimbMIRV.RData"))

print(system.time(tAfterBHMoreClimbMIRV[["mIRV=1"]] <- mclapply(c(0.01, 0.05, 0.1), function(alpha) climbMax(yAll, tree, 1, alpha, cores=3), mc.cores=3)))
save(tAfterBHMoreClimbMIRV, file = file.path(saveDir, "tAfterBHMoreClimbMIRV.RData"))
```

#### DE Analysis
```{r}
# detNodes <- list()
# negNodes <- list()
# 
# y <- tse[1:l,]
# y <- fishpond::scaleInfReps(y)
# y <- labelKeep(y)
# y <- swish(y, x="condition")
# 
# detNodes[["Txps"]] <- lapply(c(0.01, 0.05, 0.1), function(x) which(mcols(y)[,"qvalue"] <= x ))
# detNodes[["tAfterBHMoreClimbMIRV=0"]] <- lapply(tAfterBHMoreClimbMIRV[[1]], function(ta) ta)
# detNodes[["tAfterBHMoreClimbMIRV=0.4"]] <- lapply(tAfterBHMoreClimbMIRV[[2]], function(ta) ta)
# detNodes[["tAfterBHMoreClimbMIRV=1"]] <- lapply(tAfterBHMoreClimbMIRV[[3]], function(ta) ta)
# detNodes[["term"]] <- lapply(c(0.01, 0.05, 0.1), function(x) {
#         nodes <- rownames(yAggTermThrNS)[which(mcols(yAggTermThrNS)[,"qvalue"] <= x)]
#         match(nodes, names(logFCNodesTerm))
# })
# 
# negNodes[["Txps"]] <- lapply(detNodes[["Txps"]], function(nodes) setdiff(seq(l), 
#                                                           unlist(Descendants(tree, nodes))))
# negNodes[["tAfterBHMoreClimbMIRV=0"]] <- lapply(detNodes[["tAfterBHMoreClimbMIRV=0"]], function(nodes) setdiff(seq(nrow(y)), unlist(Descendants(tree, nodes)))) 
# negNodes[["tAfterBHMoreClimbMIRV=0.4"]] <- lapply(detNodes[["tAfterBHMoreClimbMIRV=0.4"]], function(nodes) setdiff(seq(nrow(y)), unlist(Descendants(tree, nodes)))) 
# negNodes[["tAfterBHMoreClimbMIRV=1"]] <- lapply(detNodes[["tAfterBHMoreClimbMIRV=1"]], function(nodes) setdiff(seq(nrow(y)), unlist(Descendants(tree, nodes))))
# negNodes[["term"]] <- lapply(c(0.01, 0.05, 0.1), function(x) {
#         nodes <- rownames(yAggTermThrNS)[setdiff(seq(nrow(yAggTermThrNS)),
#                                                  which(mcols(yAggTermThrNS)[,"qvalue"] <= x))]
#         match(nodes, names(logFCNodesTerm))
#     })
```
