---
title: "Untitled"
output: html_document
date: "2023-02-02"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

#### Loading Packages
```{r}
setwd('/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
suppressPackageStartupMessages(source("tree_helper_function.R"))
suppressPackageStartupMessages(source("tree_term_climb.R"))
suppressPackageStartupMessages(library(beaveR))

saveDir <- "environment/brain_sim_nodtu_lowfc/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/DE"
load(file=file.path(saveDir, "tseCons.RData"))

tree <- rowTree(tse)
l <- length(tree$tip)
```

#### Swish on the entire dataset 
```{r}
yAll <- computeSizeFactors(tse)
yAll <- scaleInfReps(yAll)
yAll <- labelKeep(yAll)
set.seed(1)
yAll <- swish(yAll, x = "condition")
```

#### Distribution of signs and levels
```{r}
minInfRV <- 0.20
nLeaf <- length(tree$tip)
#mIRV_cut <- cut(mIRVDiff[nLeaf+1:tree$Nnode], breaks = quantile(mIRVDiff[nLeaf+1:tree$Nnode], 0:4/4), include.lowest = T)
#print(table(mIRV_cut))
#termThresh <- quantile(mIRVDiff[nLeaf+1:tree$Nnode], 0.75)
signs <- computeSign(yAll, "condition")
print(table(signs))
levels <- node.depth(tree, 2)
levels <- ifelse(levels > 4, 5, levels)
print(table(levels))
print(table(signs, levels))
```

#### Run climbR no stop
```{r}
print(system.time(tAfterNoStop <- runTreeTermAlphas(tree, yAll, "condition", -10000, pCutOff = 0.05, pChild = 0.05, runType = c("a"), corr = c("BH"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T, temp=T, cSign=F)))
save(tAfterNoStop, file = file.path(saveDir, "tAfterNoStop.RData"))
```

#### No Sign
```{r}
print(system.time(tAfterNoSign <- runTreeTermAlphas(tree, yAll, "condition", 0.20, pCutOff = 0.05, pChild = 0.05, runType = c("a"), corr = c("BH"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T, temp=T, cSign=F)))
save(tAfterNoSign, file = file.path(saveDir, "tAfterNoSign.RData"))
```

#### All Restrictions
```{r}
print(system.time(tAfter <- runTreeTermAlphas(tree, yAll, "condition", 0.20, pCutOff = 0.05, pChild = 0.05, runType = c("a"), corr = c("BH"), alphas = c(0.01, 0.05, 0.10), cores = 3, compPThresh = T, temp=T)))
save(tAfter, file = file.path(saveDir, "tAfter.RData"))
```
