---
title: "Tree DE"
output: html_document
date: "2023-02-01"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

#### Creating TSE experiment
```{r}
setwd('/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
suppressPackageStartupMessages(source("tree_helper_function.R"))
suppressPackageStartupMessages(source("tree_term_climb.R"))
suppressPackageStartupMessages(library(beaveR))
saveDir <- "environment/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/comp_trees/DE"

clustFile <- "../brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/terminus/no_threshold0/cluster_nwk.txt"
quantDir <- file.path("../brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/out_sal") 
samples <- as.vector(outer(c(1:6), c(1,2), function(x,y) paste(x,y,sep='_')))
quantFiles <- file.path(quantDir, samples, 'quant.sf')
coldata <- data.frame(files=quantFiles, names=samples, condition=factor(rep(1:2, each=6)))
# tseConsUp <- buildTSE(clustFile, coldata)
```

#### Loading Terminus
```{r}
# suppressPackageStartupMessages(source("old_terminus_helper.R"))
# termDir <- "/fs/cbcb-lab/rob/students/noor/Uncertainity/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100/terminus"
# treeCons <- rowTree(tseConsUp)
# l <- length(treeCons$tip)
# termGroupDf <- read.delim(file.path(termDir, "old", "1_1", "clusters.txt"), header=F)
# termTxps <- unlist(sapply(strsplit(termGroupDf$V1, split = ",", fixed = T), function(x) x[2:length(x)]))
# 
# if(!all(termTxps %in% rownames(tseConsUp)[1:l])) {
#     dir <- "/fs/cbcb-lab/rob/students/noor/Uncertainity/brain_sim_nodtu/mode=gc_bias/post_type=gibbs_nrep=100_tf=100"
#     clustFile <- file.path(dir, "/terminus/no_threshold0/cluster_nwk.txt")
#     quantDir <- file.path(dir,"out_sal")
#     samples <- as.vector(outer(c(1:6), c(1,2), function(x,y) paste(x,y,sep='_')))
#     quantFiles <- file.path(quantDir, samples, 'quant.sf')
#     coldata <- data.frame(files=quantFiles, names=samples, condition=factor(rep(1:2, each=6)))
#     txps <- c(rownames(tseConsUp)[1:l], unlist(termTxps))
#     tseConsUp <- buildTSE(treeTermFile = clustFile, coldata = coldata, txps = txps)
# }
# save(tseConsUp, file=file.path(saveDir, "tseConsUp.RData"))
load(file.path(saveDir, "tseConsUp.RData"))
treeCons <- rowTree(tseConsUp)
l <- length(treeCons$tip)
```

#### Swish on the entire dataset 
```{r}
yAll <- computeSizeFactors(tseConsUp)
yAll <- scaleInfReps(yAll)
yAll <- labelKeep(yAll)
set.seed(10)
yInn <- swish(yAll[(l+1):nrow(yAll),], x = "condition")
set.seed(10)
yTxps <- swish(yAll[1:l,], x = "condition")
```

#### Distribution of signs and levels
```{r}
#mIRV_cut <- cut(mIRVDiff[nLeaf+1:tree$Nnode], breaks = quantile(mIRVDiff[nLeaf+1:tree$Nnode], 0:4/4), include.lowest = T)
#print(table(mIRV_cut))
#termThresh <- quantile(mIRVDiff[nLeaf+1:tree$Nnode], 0.75)
signs <- computeSign(yAll, "condition")
print(table(signs))
levels <- node.depth(treeCons, 2)
levels <- ifelse(levels > 4, 5, levels)
print(table(levels))
print(table(signs, levels))
```

#### Running 
```{r}
pvals <- c(mcols(yTxps)[["pvalue"]],mcols(yInn)[["pvalue"]])
mIRV <- mcols(yAll)[["meanInfRV"]]

treeDEFDR_OL <- list() ## Only leaf
print(system.time(treeDEFDR_OL[["mIRV=0.4"]] <- mclapply(c(0.01, 0.05, 0.1), function(alpha) climbMax(pvals, mIRV, treeCons, 0.4, alpha, signs, cores=3), mc.cores=3)))
save(treeDEFDR_OL, file = file.path(saveDir, "treeDEFDR_OL.RData"))
```
