```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

#### Loading TSE experiment
```{r}
setwd('/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
suppressPackageStartupMessages(source("tree_helper_function.R"))
suppressPackageStartupMessages(source("tree_term_climb.R"))
suppressPackageStartupMessages(library(pracma))
suppressPackageStartupMessages(library(beaveR))
suppressPackageStartupMessages(library(treeclimbR))
saveDir <- "environment/real_datasets/GSE100505_EDL_MAST/mode_gcbias=True/posttype=gibbs_npost=100_tf=100/DE"
load(file=file.path(saveDir, "tseConsUp.RData"))
tree <- rowTree(tseConsUp)
l <- length(tree$tip)
```

#### Swish on the entire dataset 
```{r}
saveDir <- "treeDE_Paper_Images/mousemuscle"
yAll <- computeSizeFactors(tseConsUp)
yAll <- scaleInfReps(yAll)
yAll <- labelKeep(yAll)
set.seed(1)

set.seed(10)
yTxps <- swish(yAll[1:l,], x = "condition")
print(sum(mcols(yTxps)[["qvalue"]] <= 0.1, na.rm = T))

set.seed(10)
yInn <- swish(yAll[(l+1):nrow(yAll),], x = "condition")
mcols(yAll)[["pvalue"]] <- c(mcols(yTxps)[["pvalue"]], mcols(yInn)[["pvalue"]])
infReps <- fishpond:::getInfReps(yAll)
mcols(yAll)[["log2FC"]] <- fishpond:::getLog2FC(infReps, colData(yAll)[["condition"]])
pvals <- mcols(yAll)[["pvalue"]]
```


#### Single cores
```{r}
trenDiNodes <- vector(mode="list", length=3)
alphas <- c(0.01, 0.05, 0.1)
for(i in seq_along(alphas)) {
    tic()
    print(system.time(trenDiNodes[[i]] <- trenDi::trenDi(yAll, x="condition", pvalues=pvals, 
        minP=0.7, alpha=alphas[i])))
    toc()
}
```

#### Multiple cores
```{r}
alphas <- c(0.01, 0.05, 0.1)
tt <- vector(mode="list", length=3)
for(i in seq_along(alphas)) {
    tic()
    print(system.time(tt[[i]] <- trenDi::trenDi(yAll, x="condition", pvalues=pvals, 
        minP=0.7, alpha=alphas[i], cores = 4)))
    toc()
}
```

```{r}
print(sapply(seq_along(tt), function(i) {
    sum(sort(tt[[i]])!=sort(trenDiNodes[[i]]))==0
    }))
saveDir <- "treeDE_Paper_Images/mousemuscle"
save(trenDiNodes, file=file.path(saveDir, "trenDiNodes.RData"))
```
