---
title: "Tree Terminus ClimbR on whole transcriptome"
output: html_notebook
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = '/fs/cbcb-lab/rob/students/noor/Uncertainity/treeTerminusScripts')
```

#### Loading data
```{r}
source("tree_helper_function.R")
source("tree_term_climb.R")
load("environment/whole_txp/swish_y.RData")
load("environment/whole_txp/ySwishAllNodes.RData")
load("environment/whole_txp/tree.RData")
load("../mikelove-swimdown-216a1dd/simulate/data/simulate.rda")
```


#### Visualizing infRVs(difference) for the inner Nodes
```{r}
infRVs <- mcols(yAll)[["meanInfRV"]]
mIRVDiff <- computeInfRVDiff(tree, yAll)

mIRV_cut <- cut(mIRVDiff[nrow(y)+1:tree$Nnode], breaks = quantile(mIRVDiff[nrow(y)+1:tree$Nnode], 0:4/4), include.lowest = T)
print(table(mIRV_cut))
IRV_cut <- cut(infRVs[nrow(y)+1:tree$Nnode], breaks = quantile(infRVs[nrow(y)+1:tree$Nnode], 0:4/4), include.lowest = T)
print(table(IRV_cut))

termSwimThresh <- mean(c(-3.8223631318627858,-3.6433994917165045,-3.6568587953449123,-3.7615266573162742,-3.74218233312281,
    -3.7825084537263063,-3.681508024209264,-3.6888354232562355,-3.811711665323895,-3.7328311655820956,-3.6988339545709255,-3.892522972438748))

print(mean(mIRVDiff[nrow(y)+1:tree$Nnode] <= termSwimThresh)) ### Based on difference
print(mean(infRVs[nrow(y)+1:tree$Nnode] > 0.176)) ### Based on actual inferential variance

print(mean(infRVs[nrow(y)+1:tree$Nnode] > 0.176 & mIRVDiff[nrow(y)+1:tree$Nnode] <= termSwimThresh))

mP <- mIRVDiff[nrow(y)+1:tree$Nnode][mIRVDiff[nrow(y)+1:tree$Nnode] >= 0]
mN <- mIRVDiff[nrow(y)+1:tree$Nnode][mIRVDiff[nrow(y)+1:tree$Nnode] < 0]
hist(log10(mP)) ##Positive differences
hist(log10(abs(mN))) ##Negative differences
hist(log10(infRVs[nrow(y)+1:tree$Nnode]))
```
Around 55% inner nodes match that meet boths the above criteria

#### A look at signs of the nodes/txps
```{r}
levels <- node.depth(tree, 2)
levels <- ifelse(levels > 4, 5, levels)

signs <- computeSign(yAll, "condition")
table(signs)
table(signs, levels)
```

#### Running the tree
```{r}
# tBefore <- runTreeTermAlphas(tree, yAll, "condition", termSwimThresh, pCutOff = 0.05, ihwType = c("b"), alphas = c(0.01, 0.05, 0.10), cores = 3)
tAfter <- runTreeTermAlphas(tree, yAll, "condition", termSwimThresh, pCutOff = 0.05, ihwType = c("a"), alphas = c(0.01, 0.05, 0.10), cores = 3)
# save(tBefore, file = "environment/treeTerm/tBefore.RData")
save(tAfter, file = "environment/treeTerm/tAfter.RData")
```


### Variations to run upon
before/after IHW, FDR - 0.1-0.1, varying pvalues, different stopping criteria based on IVAR, no stopping criteria based on infRV
run on entire tree, only tree